---
- name: xxxxx
  command: sh /opt/getip.sh
  changed_when: '"Nothing to install or update" not in nodeip.stdout'
- name: yyyyy
  command: sh /opt/sedip.sh
  notify: restart emq
  changed_when: '"Nothing to install or update"'
