---
- name: nodeip
  vars:
    nodeip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
- name: sedip
  command: /usr/bin/sh /opt/sedip.sh
  changed_when: False
  notify: restart emq
