---
- name: check_ip
  shell: |
  set -o pipefail
  ip a | grep -w "inet" | grep ens33 |sed 's/^.*inet //g'|sed 's/\/[0-9][0-9].*$//g'
  register: nodeip
- name: change_ip_and_sed
  shell: |
  set -o pipefail
  sed -i 's#nodeip#{{ nodeip['stdout'] }}#g' /etc/emqttd/emq.conf
  notify: restart emq
