---
- name: getip
  command: /usr/bin/sh /opt/getip.sh
  register: nodeip
  changed_when: "nodeip.rc != 0"
- name: sedip
  command: /usr/bin/sh /opt/sedip.sh
  changed_when: False
  notify: restart emq
