---
- name: install yum-utils
  yum: name=yum-utils state=present
- name: install lksctp-tools
  yum: name=lksctp-tools state=present
- name: install emq
  yum: name=/opt/emqttd-centos7-v2.3.11-1.el7.centos.x86_64.rpm state=present
- name: copy conf file and restart emq
  copy: src=emq.conf dest=/etc/emqttd/emq.conf
  notify: restart emq
- name: enable emq service
  service: name=emqttd.service enabled=yes
