---
- name: yum install software
  yum: name="{{ item }}" state=absent
  with_items:
  - wget
  - yum-utils
  - lksctp-tools
  - \*epel\*
  - gcc-c++
  - unixODBC
  - unixODBC-devel
  - openssl-devel
  - ncurses-devel
  - libxml2-utils
  - xsltproc
  - fop
  - gtk2-devel
  - binutils-devel
  - perl
- name: install socat
  yum: name=/opt/socat-1.7.3.2-2.el7.x86_64.rpm state=present
- name: install socat
  yum: name=/opt/erlang-20.3.8.4-1.el7.centos.x86_64.rpm state=present
- name: install otp
  command: sh otpinstall.sh
  changed_when: "true"
- name: install emq
  yum: name=/opt/emqttd-centos7-v2.3.11-1.el7.centos.x86_64.rpm state=present
- name: copy conf file and restart emq
  copy: src=emq.conf dest=/etc/emqttd/emq.conf
  notify: restart emq
- name: enable emq service
  service: name=emqttd.service enabled=yes
